server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  #spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:  #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI5tEDLT5vu27M2cBr6U5Z #你的keyid
    key-secret: BX5yarC86BzxGG4o0aPEtrVIV6ShNn #你的keysecret
    template-code: SMS_217425770 #你的短信模板code
    sign-name: 北京课时教育 #%E5%8C%97%E4%BA%AC%E8%AF%BE%E6%97%B6%E6%95%99%E8%82%B2 #你的短信模板签名